export const LOGIN = "LOGIN";
export const REGISTER = "REGISTER";
export const CONFIRM_ACCOUNT = "CONFIRM_ACCOUNT";
export const REFRESH_CREDENTIALS = "REFRESH_CREDENTIALS";
export const LOGOUT_ACTION = "LOGOUT_ACTION";
